version: '3.8'

services:
  whisper_metrics:
    build:
      context: ./exporters
      dockerfile: Dockerfile
    command: python whisper_metrics.py
    environment:
      - METRICS_PORT=9090
      - PYTHONUNBUFFERED=1
    ports:
      - "9090:9090"
    volumes:
      - ./exporters:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - metrics_net

  piper_metrics:
    build:
      context: ./exporters
      dockerfile: Dockerfile
    command: python piper_metrics.py
    environment:
      - METRICS_PORT=9091
      - PYTHONUNBUFFERED=1
    ports:
      - "9091:9091"
    volumes:
      - ./exporters:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - metrics_net

  openwakeword_metrics:
    build:
      context: ./exporters
      dockerfile: Dockerfile
    command: python openwakeword_metrics.py
    environment:
      - METRICS_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - "9092:9092"
    volumes:
      - ./exporters:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - metrics_net

networks:
  metrics_net:
    driver: bridge
