name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./exporters
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      working-directory: ./exporters
      run: bash test_collectors.sh

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      working-directory: ./exporters
      run: docker build -t ha-ai-exporters .

  verify-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check YAML syntax
      run: |
        pip install yamllint
        yamllint -d '{extends: default, rules: {line-length: disable}}' .
        
    - name: Validate Docker Compose
      run: |
        docker-compose -f docker-compose.test.yml config
