name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd exporters
        pip install -r requirements.txt
        pip install pylint pytest pytest-cov

    - name: Run tests
      run: |
        cd exporters
        ./test_collectors.sh

    - name: Run linting
      run: |
        cd exporters
        pylint *.py --disable=C0111,C0103

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      run: |
        docker buildx create --use
        cd exporters
        docker buildx build --platform linux/amd64,linux/arm64 .

  verify-configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Prometheus
      run: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
        tar xvf prometheus-*.tar.gz
        
    - name: Validate Prometheus config
      run: |
        ./prometheus-*/promtool check config prometheus.yaml
        ./prometheus-*/promtool check rules alerts.yml

    - name: Validate Docker Compose
      run: |
        docker-compose -f docker-compose.test.yml config
